### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by webglo** [Owen-Cochell/mctools#14]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Scripts\mcli.exe\__main__.py", line 7, in <module>
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Lib\site-packages\mctools\__main__.py", line 389, in main
    val = rcon.authenticate(args.password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Lib\site-packages\mctools\mclient.py", line 396, in authenticate
    return self.login(password)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Lib\site-packages\mctools\mclient.py", line 370, in login
    pack = self.raw_send(self.proto.LOGIN, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Lib\site-packages\mctools\mclient.py", line 297, in raw_send
    pack = self.proto.read()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Lib\site-packages\mctools\protocol.py", line 282, in read
    pack = RCONPacket.from_bytes(byts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Lib\site-packages\mctools\packet.py", line 87, in from_bytes
    reqid, reqtype, payload = RCONEncoder.decode(byts)
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stude\AppData\Local\Programs\Python\Python311\Lib\site-packages\mctools\encoding.py", line 96, in decode
    reqid, reqtype = struct.unpack("<ii", byts[:8])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 8 bytes

**Comment by Owen-Cochell** [comment]
Hello.

Thanks for reporting this! I have tested mctools against the latest version of the minecraft server, and I have seen no issues. Could you send me the code you are attempting to run, along with the version of the server you are running? Also, be sure that you are running the latest version of mctools:

```bash
pip install -U mctools
```

This issue seems very odd, so we should make sure you are running the latest version. Thanks for reporting this, hopefully we can figure this out.

**Comment by davirxavier** [comment]
Having the same issue while trying to run the RCON broadcast example at the introduction:

`from mctools import RCONClient  # Import the RCONClient

HOST = 'mc.server.net'  # Hostname of the Minecraft server
PORT = 1234  # Port number of the RCON server

# Create the RCONClient:

rcon = RCONClient(HOST, port=PORT)

# Login to RCON:

if rcon.login("password"):

    # Send command to RCON - broadcast message to all players:

    resp = rcon.command("broadcast Hello RCON!")`

Using the latest version and using Python3 with venv on clean project generated by PyCharm.

**Comment by Owen-Cochell** [comment]
Hey sorry for the response delay, I have been traveling.

I can't seem to reproduce this error. I am testing the latest mctools against the latest minecraft server, `1.20.1`. I have tried this on the vanilla server jar, as well as PaperMC.

@davirxavier or @webglo would you mind sending me some info on the server you are attempting to connect to? It's version, type (PaperMC, bukkit, vanilla, etc), installed plugins, or any other interesting networking details. Also, are you sure the host you are connecting to is a minecraft server? This error could occur if the service listening at the provided host/port is not a minecraft server. Hopefully that will bring us closer to solving this.

If this is a public server, I would like the connection information so I can do some testing myself. If this is a private server and you are not comfortable with me talking to it, then I can create a debug version of mctools that will output some information that would be useful for debugging.

Please let me know about these details. if this is an mctools bug then I would like to get it fixed.

Thanks!
